Home
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #10
Opened 2022-01-03 16:13 UTC by clairedelaleau

Home is done. Please, can you check this.

2022-01-03 16:36 UTC, HeloiseFerla requested changes

2022-01-03 16:36 UTC, HeloiseFerla commented on src/pages/Home/index.jsx
> +              <img src={Office} alt={Office} />
You can't put a picture in alt.

2022-01-03 16:36 UTC, HeloiseFerla commented on src/pages/Home/index.jsx
> +              <img src={Furnitures} alt={Furnitures} />
same

2022-01-03 16:36 UTC, HeloiseFerla commented on src/pages/Home/index.jsx
> +            <div className="pictureCard">
same

2022-01-03 16:36 UTC, HeloiseFerla commented on src/pages/Home/index.jsx
> +          <article className="lostcard">
className in CamelCase Plz

2022-01-03 16:36 UTC, HeloiseFerla commented on src/pages/Home/index.jsx
> +            <div className="picturefurniture">
ClassName in camelCase plz

2022-01-06 14:35 UTC, HeloiseFerla approved these changes

2022-01-06 15:13 UTC, Hacene010 approved these changes

2022-01-06 15:38 UTC, closed without merging