Meeting
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #12
Opened 2022-01-04 15:43 UTC by HeloiseFerla

2022-01-04 16:40 UTC, BBriset reviewed
Dont think we need that "tatus" files, otherwise great job!

2022-01-05 09:05 UTC, BBriset submitted a review, later dismissed
good according to me

2022-01-05 09:33 UTC, BBriset approved these changes, later dismissed

2022-01-05 11:28 UTC, LoicBrassart requested changes
I'm almost you don't need all those `z-index`

2022-01-05 11:28 UTC, LoicBrassart commented on src/App.jsx
> +        <Route path="ProfilPage" element={<ProfilPage />} />
Be consistent about your routes' case (upper vs lower)

2022-01-05 11:28 UTC, LoicBrassart commented on src/pages/Meeting/Room/Share/SharePopup/style.jsx
> +  }
Indentation problem. Isn't Prettier installed ?

2022-01-05 13:53 UTC, BBriset approved these changes

2022-01-05 14:18 UTC, LoicBrassart approved these changes
NmE

2022-01-05 14:30 UTC, merged