ProfilePage static, and minor improvement on loginPage
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #15
Opened 2022-01-05 16:48 UTC by BBriset

2022-01-06 14:33 UTC, HeloiseFerla requested changes

2022-01-06 14:33 UTC, HeloiseFerla commented on src/pages/Profile/style.jsx
> +  .UserCard {
CamelCase ?

2022-01-07 12:53 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-10 09:43 UTC, Hacene010 requested changes

2022-01-10 09:43 UTC, Hacene010 commented on src/pages/Profile/index.jsx
>  const solde = '37,64€';
you could put your data into an object : )

2022-01-10 09:43 UTC, Hacene010 commented on src/pages/Profile/style.jsx
> +
empty lines

2022-01-12 14:32 UTC, HeloiseFerla requested changes

2022-01-12 14:32 UTC, HeloiseFerla commented on src/pages/Profile/style.jsx
> +}
indentation

2022-01-12 14:54 UTC, HeloiseFerla approved these changes

2022-01-13 11:01 UTC, Hacene010 approved these changes

2022-01-13 11:12 UTC, merged