Global style
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #19
Opened 2022-01-12 13:42 UTC by Quentin-Macquart

Hey Heloise, 
I add the globalStyle in all major parts. I did still have the problem transferring the dark mode to others files. I let you check before we have a debug session with Loic. I made all the correction the client asked for too. 

There are a plenty of files modified, but don't worry about it it's only conditions and css added. 
Happy reading!

2022-01-12 14:08 UTC, HeloiseFerla commented on src/pages/Food/BurgerMenu/index.jsx
> +        <section>
path in camelCase

2022-01-12 14:16 UTC, HeloiseFerla requested changes

2022-01-12 14:16 UTC, HeloiseFerla commented on src/pages/Office/index.jsx
> +import Header from '../../components/Header';
components/ ...

2022-01-12 14:22 UTC, Quentin-Macquart commented on src/pages/Food/BurgerMenu/index.jsx
> +        <section>
Mh...

2022-01-12 14:33 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-13 09:47 UTC, Hacene010 requested changes
Saw some evils :-)

2022-01-13 09:47 UTC, Hacene010 commented on src/pages/Food/FoodProfile/index.jsx
> +          <p className="votreProfil">Votre profil alimentaire</p>
className in french ???

2022-01-13 09:47 UTC, Hacene010 commented on src/pages/Home/style.jsx
>      display: flex;
With a display:flex; only, you don't need a flex-direction:row;, don't you ?

2022-01-13 11:19 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-13 11:25 UTC, Quentin-Macquart commented on src/pages/Food/FoodProfile/index.jsx
> +          <p className="votreProfil">Votre profil alimentaire</p>
I promise i got the accent when i wrote it

2022-01-13 13:03 UTC, Hacene010 approved these changes

2022-01-13 16:17 UTC, HeloiseFerla approved these changes

2022-01-13 16:17 UTC, merged