Changed the Supplies page frontend to associate it at backend
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #22
Opened 2022-01-13 10:36 UTC by Othmane-Khiter

2022-01-13 11:01 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-13 13:19 UTC, Hacene010 requested changes
Some evils

2022-01-13 13:19 UTC, Hacene010 commented on .env.dist
> +REACT_APP_API_URL=
Why 2 REACT... ?

2022-01-13 13:19 UTC, Hacene010 commented on src/pages/Supplies/index.jsx
> +// import postit from 'assets/Img/SuppliesPictures/postit.png';
dead code !!!

2022-01-14 10:49 UTC, HeloiseFerla approved these changes

2022-01-14 11:22 UTC, Hacene010 approved these changes

2022-01-14 13:46 UTC, merged