Lost card2
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #25
Opened 2022-01-14 15:33 UTC by BBriset

2022-01-17 14:03 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-17 15:46 UTC, Hacene010 requested changes
A small evil

2022-01-17 15:46 UTC, Hacene010 commented on src/pages/LostCard/index.jsx
> +              <img src={user.picture} alt="pp" />
pp will not help the blind person much :-)

2022-01-17 15:46 UTC, Hacene010 commented on src/pages/LostCard/style.jsx
> +
empty line

2022-01-18 08:18 UTC, HeloiseFerla approved these changes

2022-01-18 14:05 UTC, Hacene010 approved these changes

2022-01-18 14:31 UTC, merged