Share meeting
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #31
Opened 2022-01-18 18:26 UTC by HeloiseFerla

2022-01-18 18:36 UTC, Quentin-Macquart submitted a review, later dismissed

2022-01-19 15:24 UTC, Hacene010 requested changes

2022-01-19 15:24 UTC, Hacene010 commented on src/pages/Meeting/Room/Share/SharePopup/index.jsx
> +
empty line !

2022-01-20 08:46 UTC, Hacene010 approved these changes

2022-01-20 08:57 UTC, Quentin-Macquart approved these changes

2022-01-20 09:12 UTC, merged