Add a chat
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #38
Opened 2022-01-25 15:25 UTC by HeloiseFerla

2022-01-25 16:15 UTC, Quentin-Macquart submitted a review, later dismissed

2022-01-26 10:13 UTC, Hacene010 requested changes

2022-01-26 10:13 UTC, Hacene010 commented on src/pages/Chat/index.jsx
> +  const [socket, setSocket] = useState(socketIOClient('http://localhost:8080'));
don't forget to hide your localhost into a .env

2022-01-26 10:13 UTC, Hacene010 commented on src/pages/Chat/style.jsx
> +  ul {
Plz remove the ul if you don't need de style it

2022-01-26 13:34 UTC, Quentin-Macquart approved these changes, later dismissed

2022-01-26 13:40 UTC, Hacene010 submitted a review, later dismissed

2022-01-26 13:43 UTC, Quentin-Macquart approved these changes

2022-01-26 13:45 UTC, Hacene010 approved these changes

2022-01-26 13:46 UTC, merged