My meal
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #39
Opened 2022-01-26 11:38 UTC by Quentin-Macquart

2022-01-26 12:28 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-26 15:30 UTC, Hacene010 requested changes

2022-01-26 15:30 UTC, Hacene010 commented on src/pages/Food/FoodModal/index.jsx
> +        console.log(data);
no console.log

2022-01-27 12:09 UTC, HeloiseFerla approved these changes, later dismissed

2022-01-27 15:51 UTC, Hacene010 requested changes

2022-01-27 15:51 UTC, Hacene010 commented on src/pages/ProfilePage/Meetings/style.jsx
> +      img {
empty element

2022-01-28 16:13 UTC, HeloiseFerla approved these changes

2022-01-28 16:26 UTC, Hacene010 approved these changes

2022-01-28 16:34 UTC, merged