Supplies back to front
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #40
Opened 2022-01-26 17:09 UTC by Quentin-Macquart

2022-01-27 07:43 UTC, HeloiseFerla requested changes

2022-01-27 07:43 UTC, HeloiseFerla commented on src/App.jsx
> +
empty line

2022-01-27 07:43 UTC, HeloiseFerla commented on src/App.jsx
> +
empty line

2022-01-27 07:43 UTC, HeloiseFerla commented on src/components/Counter/index.jsx
> +
empty line

2022-01-27 07:43 UTC, HeloiseFerla commented on src/components/Counter/index.jsx
> +
empty lines

2022-01-27 12:06 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-27 15:38 UTC, Hacene010 requested changes

2022-01-27 15:38 UTC, Hacene010 commented on src/pages/Supplies/index.jsx
> +    console.log(cart);
??

2022-01-28 16:12 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-28 16:25 UTC, Hacene010 requested changes

2022-01-28 16:25 UTC, Hacene010 commented on src/pages/Supplies/index.jsx
>          <Header logo={fournitures} />{' '}
forgot this {' '}

2022-01-28 16:53 UTC, HeloiseFerla approved these changes

2022-01-29 12:07 UTC, LoicBrassart approved these changes
SnE

2022-01-31 08:15 UTC, Hacene010 approved these changes

2022-01-31 08:58 UTC, merged