Update chat
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #41
Opened 2022-01-27 20:03 UTC by Quentin-Macquart

2022-01-28 14:57 UTC, HeloiseFerla requested changes

2022-01-28 14:57 UTC, HeloiseFerla commented on src/pages/Supplies/index.jsx
> +        <Header logo={fournitures} />{' '}
?

2022-01-28 14:57 UTC, HeloiseFerla commented on src/pages/Supplies/index.jsx
> +            />{' '}
?

2022-01-28 14:57 UTC, HeloiseFerla commented on src/pages/SuppliesModal/index.jsx
> +
empty line

2022-01-28 14:57 UTC, HeloiseFerla commented on src/pages/SuppliesModal/style.jsx
> +
empty line

2022-01-28 16:17 UTC, HeloiseFerla approved these changes, later dismissed

2022-01-28 16:30 UTC, Hacene010 requested changes

2022-01-28 16:30 UTC, Hacene010 commented on src/pages/SuppliesModal/index.jsx
> +// import { useState } from 'react';
dead code

2022-01-28 16:30 UTC, Hacene010 commented on src/pages/SuppliesModal/index.jsx
> +        console.log(data);
?

2022-01-28 17:03 UTC, HeloiseFerla approved these changes, later dismissed

2022-01-29 12:10 UTC, LoicBrassart requested changes
Several branches not created from dev -> I read several times the same code -> I'm less nice in my reviews :p

2022-01-29 12:10 UTC, LoicBrassart commented on src/pages/Chat/index.jsx
> +              }
`else` ?

2022-01-29 12:10 UTC, LoicBrassart commented on src/pages/SuppliesModal/index.jsx
> +      });
No console.log

2022-01-31 08:51 UTC, Hacene010 approved these changes, later dismissed

2022-01-31 09:31 UTC, HeloiseFerla submitted a review, later dismissed

2022-01-31 16:02 UTC, HeloiseFerla approved these changes

2022-01-31 16:52 UTC, Hacene010 approved these changes

2022-02-01 07:52 UTC, LoicBrassart approved these changes

2022-02-01 07:53 UTC, merged