Office profile
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #43
Opened 2022-01-28 14:56 UTC by Quentin-Macquart

2022-01-28 15:52 UTC, HeloiseFerla approved these changes, later dismissed

2022-01-28 16:18 UTC, Hacene010 requested changes

2022-01-28 16:18 UTC, Hacene010 commented on src/pages/Supplies/index.jsx
> +    console.log(cart);
??

2022-01-28 17:14 UTC, HeloiseFerla approved these changes, later dismissed

2022-01-31 08:46 UTC, Hacene010 approved these changes, later dismissed

2022-01-31 09:28 UTC, HeloiseFerla approved these changes

2022-01-31 15:45 UTC, Hacene010 approved these changes

2022-01-31 15:58 UTC, merged