Fix profil2
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #46
Opened 2022-01-31 13:38 UTC by BBriset

First deletation and modifications are from duplicate folder on the dev

2022-02-01 17:09 UTC, HeloiseFerla approved these changes

2022-02-01 17:09 UTC, HeloiseFerla commented on src/pages/SuppliesModal/style.jsx
> +
empty line

2022-02-01 17:09 UTC, HeloiseFerla commented on src/pages/SuppliesModal/index.jsx
> +
empty line

2022-02-01 17:09 UTC, HeloiseFerla commented on src/pages/Supplies/style.jsx
empty line

2022-02-01 17:09 UTC, HeloiseFerla commented on src/pages/Supplies/style.jsx
empty line

2022-02-01 17:10 UTC, HeloiseFerla requested changes
empty lines

2022-02-02 17:01 UTC, HeloiseFerla submitted a review, later dismissed

2022-02-04 07:58 UTC, Hacene010 submitted a review, later dismissed

2022-02-04 08:16 UTC, HeloiseFerla approved these changes

2022-02-04 08:18 UTC, Hacene010 approved these changes

2022-02-04 08:28 UTC, merged