fix supplies css
WildCodeSchool/p3-g4-sept21-lille-reactJs-eazyapp-frontend pull request #59
Opened 2022-02-07 14:44 UTC by BBriset

2022-02-07 15:54 UTC, HeloiseFerla requested changes

2022-02-07 15:54 UTC, HeloiseFerla commented on src/pages/SuppliesModal/style.jsx
> +
empty line

2022-02-08 08:00 UTC, HeloiseFerla approved these changes

2022-02-08 08:05 UTC, Hacene010 approved these changes

2022-02-08 08:14 UTC, merged